name: core
description: Stuff that can be shared across all dart projects.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  duration: ^3.0.6
  equatable: ^2.0.0
  get_it: ^6.0.0
  hive: ^2.0.0
  intl: ^0.17.0
  logger: ^1.0.0-nullsafety.0
  sembast: ^3.0.0+4
  unit_convert: ^0.1.3

dev_dependencies:
  test: ^1.15.3
