name: core
description: Stuff that can be shared across all dart projects.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  equatable: ^1.2.3
  intl: ^0.16.1
  logger: ^0.9.1

  sembast: ^2.4.3
  hive: ^1.4.2

dev_dependencies: 
  test: ^1.15.3
  

