name: core
description: Stuff that can be shared across all dart projects.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  duration: ^2.0.15
  equatable: ^1.2.5
  get_it: ^5.0.1
  hive: ^1.4.4+1
  intl: ^0.16.1
  logger: ^0.9.4
  sembast: ^2.4.8

dev_dependencies:
  test: ^1.15.3
