name: shared
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core: 
    path: ../core
  
  provider: ^5.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  cube:
    path: ../../packages/cube

  shared_preferences: ^2.0.5
  hive_flutter: ^1.0.0
  
  simple_animations: ^3.1.1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_svg: ^0.22.0
  yaml: ^3.1.0

  flutter_displaymode: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:
  uses-material-design: true