name: shared
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core: 
    path: ../core
  
  yaml: ^2.2.1

  provider: ^4.3.2+3
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  cube:
    path: ../../packages/cube

  auto_size_text: ^2.1.0
  flutter_svg: ^0.19.1

  shared_preferences: ^0.5.12+4
  hive_flutter: ^0.3.1

  flutter_displaymode: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:
  uses-material-design: true